name: Pytest

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - ci/*

env:
  DATABASE_URL: "postgres://saleor:saleor@postgres:5432/saleor"
  SECRET_KEY: ci-test

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: saleor
          POSTGRES_USER: saleor
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Install system dependencies
        run: apt-get install -y libpq-dev

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Checkout Saleor
        uses: actions/checkout@v2
        with:
          repository: mirumee/saleor

      - name: Checkout plugin
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Installing Saleor
        run: |
          python -m pip install wheel
          python -m pip install -r requirements_dev.txt

      - name: Install plugin's dependencies
        run: |
          cd plugin
          ls -a
          python setup.py install

      - name: Copy plugin to Saleor
        run: |
          cp -r plugin/excise saleor/plugins/avatax

      - name: Run tests
        run: |
          pytest saleor/plugins/avatax/excise